### ISSUE TITLE
Question: What's new and what about performance?

### ISSUE THREAD

**Issue by Ponant** [YaccConstructor/QuickGraph#160]
Hi,
First thanks for making this available on GitHub! I am new to quickgraph which I discovered recently. And I saw this fork tonight. I have two questions if you do not mind:
1) What is new with respect to the original one?
2) Can this be used in some way as a graph database (sorry I did not go through the src, yet)? Is it optimized for search (indexed, binary search or so)?
Thanks!

**Comment by gsvgit** [comment]
Hi,
Feel free to use and contribute!
1)
- Dot to QuickGraph loader (+ dot language parser)
- New algorithms (partially in F#): Yen, TSP, coloring algorithms, etc
- PCL is turned off (i hope temporary)   
2) QG is not optimized for graph DB. It is just data structures for graphs representation and algorithms on these. First of all, in QG graph always fully stored in RAM. So, it can not be used as efficient storage without changes. 
But we are working on path query language for QG. So it will be possible to use QG as data model for path querying.
