### ISSUE TITLE
Latest release on Nuget (3.7.3)

### ISSUE THREAD

**Issue by chappoo** [YaccConstructor/QuickGraph#176]
The latest package version available on NuGet.org is 3.7.3, which is some way behind what's currently been merged to master in this repo.  Is there any chance a new package can be published with the latest changes (assuming master is release-able)?

We're currently using some of the features from master (ComputeTransitiveReduction etc) which are not in the 3.7.3 release, and not having to create our own internal package would be great.

**Comment by chappoo** [comment]
Dear maintainer, are you able to provide some guidance?  Do you require some assistance with packaging / publishing?

**Comment by gsvgit** [comment]
@chappoo 
Try out v3.4.3: https://www.nuget.org/packages/YC.QuickGraph/  

Sorry for delay.
