### ISSUE TITLE
Задача коммивояжёра (travelling salesman problem)

### ISSUE THREAD

**Issue by AnastasiyaRagozina** [YaccConstructor/QuickGraph#18]
- [ ] Найти уже существующиее решение, разобраться в нём
- [ ]  Реализовать пару других подходов.
- [ ] Сравнить получившиеся решения.

**Comment by zejafo** [comment]
Я правильно понимаю, что алгоритм не реализован в рамках этой задачи?
Просто сейчас столкнулся с тем, что необходимо решить задачу близкую TSP в рамках библиотеки QuickGraph.

В общем, я примерно представляю, как можно решить свою задачу, но думал, что в этом проекте есть какая-то готовая реализация.

**Comment by gorohovart** [comment]
Looks like algo that you need:
https://github.com/YaccConstructor/QuickGraph/tree/master/src/QuickGraph/Algorithms/TSP

**Comment by zejafo** [comment]
@gorohovart Thanks!

I will try to adapt this implementation to my task.

**Comment by zejafo** [comment]
@gorohovart 

I looked into TSP defenition and found, that my problem is related to original TSP, but not equal.
My problem described in [this](http://stackoverflow.com/questions/222413/find-the-shortest-path-in-a-graph-which-visits-certain-nodes) stackoverlow question.

> _I need to find the shortest path through this graph that starts at 'start', ends at 'end', and passes through all of the 'mustpass' nodes (in any order)_

So, now my question is how to adopt TSP algo to my task.
