### ISSUE TITLE
Domatic partition

### ISSUE THREAD

**Issue by AnastasiyaRagozina** [YaccConstructor/QuickGraph#20]
Partition of vertices into disjoint dominating set. Calculate domatic number.

**Comment by resaglow** [comment]
Тестировать нужно только соответствие domatic number-а? Разбиений просто обычно много, прям хардкодить в тесте все возможные?

**Comment by AnastasiyaRagozina** [comment]
Сделайте пару тестов с захордкоженными разбиениями, а остальные только на соответствие domatic number.
