### ISSUE TITLE
Graph gomomorphism

### ISSUE THREAD

**Issue by AnastasiyaRagozina** [YaccConstructor/QuickGraph#25]
Реализовать алгоритм. Just do it!

**Comment by octomarat** [comment]
Жаль на гитхабе лайки нельзя ставить, а то я уже подвидосом с Шаей к одному из предыдущих issue хотел поставить)

**Comment by gsvgit** [comment]
https://github.com/yoadsn/ArrowDiagramGenerator/blob/master/QuickGraph.TransitiveReduction/TransitiveReductionAlgorithm.cs
