### ISSUE TITLE
Интерфейс для визуализации алгоритмов

### ISSUE THREAD

**Issue by AnastasiyaRagozina** [YaccConstructor/QuickGraph#27]
Создать пользовательский интерфейс для визуализации алгоритмов на графах. 
* [x] Чтение данных из dot
   * [x] Переместить DotParserProject в общую структуру (\src\QuickGraph.)
   * [x] Больше тестов. Уже всплыла как минимум одна проблема: https://github.com/YaccConstructor/YaccConstructor/pull/145. Смотреть первое сообщение.
   * [x] из файла
   * [x] текстовое окно ввода
       * [x] Удобно воспользоваться этим тулом http://avalonedit.net/
* [x]  [GraphX](https://graphx.codeplex.com/) для отрисовки графов
   * [x] Реализовать конвертер графов QuickGraph в графы GraphX 
* [ ] Для раскладки комнонент использовать [avalonDock](https://avalondock.codeplex.com/)
* [x] Возможность пошагового проигрывания алгоритма
* [x] Список доступных алгоритмов
* [x] Расширяемость списка алгоритмов

**Comment by auduchinok** [comment]
Добавил [README](https://github.com/YaccConstructor/QuickGraph/blob/92cfbd70ba9c9db486c3a31ce69401854bfdb2d8/src/GraphTask.PluginSample/README%20(Russian).md) с решениями проблем, с которыми столкнулись часть ребят.

Думаю, можно закрыть issue.

**Comment by gsvgit** [comment]
Здорово. Спасибо.
