### ISSUE TITLE
Улучшить Grammar Flow Graph

### ISSUE THREAD

**Issue by AnastasiyaRagozina** [YaccConstructor/QuickGraph#36]
* [x] Реализовать группировку вершин.
* [ ] Применить другие средства визуализации: GraphX, GraphSharp, MSVS Diagrams

[Детали здесь](https://github.com/YaccConstructor/YaccConstructor/issues/137)

**Comment by ascherbakhov** [comment]
Отпишусь для себя, чтобы не забыть: насчет группировки вершин в GraphX - там эта фича не реализована
"Hi i think it would be very complicated task. Honestly, i'm not sure if this feature is ever on demand
...
"
Полное описание issue:
https://github.com/panthernet/GraphX/issues/12

**Comment by ascherbakhov** [comment]
https://www.yworks.com/products/yfiles-net
Здесь группировка графов реализована.
А в GrapSharp тоже все грустно: пара туториалов, плоский функционал и нет документации. С QuickGraph и не сравнится

**Comment by ascherbakhov** [comment]
А вот в этой версии QuickGraph кластеризация графов реализована
http://mb-unit.googlecode.com/svn/branches/v2.4/quickgraph/QuickGraph.Algorithms.Graphviz/GraphvizAlgorithm.cs
