### ISSUE TITLE
Алгоритм Йена

### ISSUE THREAD

**Issue by AnastasiyaRagozina** [YaccConstructor/QuickGraph#37]
- [x] Реализовать алгоритм Йена поиска k кратчайших путей.
- [x] Визуализировать алгоритм
- [x] реализовать пожелания

**Comment by gsvgit** [comment]
А давайте сделаем так, чтобы
1)  алгоритм мог принимать функцию получения веса по ребру.
2) алгоритм мог принимать ограничение для поиска: т.е. не просто k кратчайших, а скажем, все пути, у кого вес меньше N
