### ISSUE TITLE
Проверка свойств графа

### ISSUE THREAD

**Issue by AnastasiyaRagozina** [YaccConstructor/QuickGraph#38]
Реалиизовать и визуализировать алгоритмы проверки
* [ ]  эйлеровости графа
* [ ] гамильтоновости графа
    * [ ] обязательно реализовать алгебраический метод.

**Comment by fedorovr** [comment]
Можете ли вы указать более подробное описание алгебраического метода нахождения гамильтонова цикла, в слайдах не очень понятно написано, а самостоятельно описание алгоритма я не нашел
https://www.google.ru/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=hamilton%20path%20algorithm%20matrix

![image](https://cloud.githubusercontent.com/assets/6783143/15710737/ea7a19c2-2813-11e6-98e8-5438c770a05d.png)

**Comment by AnastasiyaRagozina** [comment]
http://educ.jmu.edu/~lucassk/Papers/determinant.pdf а это оно?

**Comment by fedorovr** [comment]
Вообще не совсем, в статье составляется система из E+2V+1 уравнений и решается с помощью базиса Гребнера и алгоритма Buchberger’s из пакета Maple.

**Comment by fedorovr** [comment]
Там еще написано, что можно посчитать определитель матрицы VxV и проверить слагаемые, являются ли они гамильтоновыми циклами. Не понятно, чем это лучше просто перебора, и там и там V! вариантов надо проверить.

**Comment by gsvgit** [comment]
Лучше оно потому, что матрицы известно как эффективно перемножать для больших графов.

**Comment by gsvgit** [comment]
Вообще, надо будет поэкспериментрировать с этим.
