### ISSUE TITLE
Transitive Reduction Algorithm

### ISSUE THREAD

**Issue by yoadsn** [YaccConstructor/QuickGraph#4]
Hey,
I have had a need to use transitive reduction algorithm for some project I am working on. I am willing to contribute the code I used inspired by some matlab library I found(It is based off of V3.0 ). Not sure I will have enough time to implement proper testing thought.

Would that we OK for me to submit a PR ?

Thanks!

**Comment by gsvgit** [comment]
Hi!

Yes, please submit PR.  Don't worry about tests. Note that we have temporarily turned off PCL library building due to some problems with build automation and code contracts. So NuGet package contains  .NET 3.5 version only.

**Comment by yoadsn** [comment]
Alright, I kinda drifted on working on something else but I think I can still make it. If not, I would update this issue to be closed.

Thank you for your patience!

**Comment by gsvgit** [comment]
@RomanBelkov can we close this issue?

**Comment by RomanBelkov** [comment]
Yes, I think so.

@yoadsn I've refactored your code a bit and merged your code along with a couple of basic tests in QG. I've made a note that original code is written by you and not me, so, I guess, everything is just.

If you'd like to add some tests or edit the code -- you are always welcome!

**Comment by yoadsn** [comment]
Sorry for not making it to a working PR, I drifted too far.
Glad you could find the time to scavenge something useful - thanks for the attribution!
