### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/QuickGraph#8]
Create a cool logo.

**Comment by dandruk** [comment]
I have a couple ideas. Do I make a new branch just for this, or just upload the files here? I'm new to github contributing.

**Comment by gsvgit** [comment]
@dandruk The best way is [pull request](https://help.github.com/articles/using-pull-requests/) (or PR). You can create PR to master branch. Right place for files is docs/files/img. There is only default F# logo in this folder now. You can replace it with your files.
